### ISSUE TITLE
Missing a lot of files and can't compile

### ISSUE THREAD

**Issue by antonclaeys** [debsahu/esp8266-arduino-aws-iot-ws#1]
I'm trying to compile in the Arduino IDE for ESP8266, but it keeps telling me I'm missing a lot of files: IPstack.h, MQTTClient.h, etc. Can you list all required libraries in order for this to work properly?

Thanks!

**Comment by debsahu** [comment]
Video instructions will be public tomorrow on YouTube. The link is in the README as well.
