### ISSUE TITLE
posts to test topics arrive as string not json

### ISSUE THREAD

**Issue by holla2040** [debsahu/esp8266-arduino-aws-iot-ws#3]
when using the aws mqtt test interface, my pubs to a test topic aren't displayed as json but utf-8.  Can the arduino mqtt specify that message payloads are json or is everything just a string?

Also there's 1 extra null char after this text in the payload

{
  "format": "string",
  "payload": "{test:1}\u0000",
  "qos": 0,
  "timestamp": 1544311404479,
  "topic": "test"
}

in your int AWSMqttClient::publish method, you send the wrong length to client.publish. Here's my fix
  return client.publish(topic, pl, strlen(payload), qs, retained);

**Comment by debsahu** [comment]
no longer maintained, please use a more direct approach to connect to AWS IoT core: https://github.com/debsahu/ESP-MQTT-AWS-IoT-Core
